Controls
--------


We start off by creating the ship. It is controlled by the left and right arrow keys and moves
on the periphery of an imaginary circle.

== Model

We first setup the model for the `Game` which contains the `Player` with the position (represented by an angle), the current 'direction' in which the player is moving and a `keyboardModel`:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/controls/src/Hexagon.elm", lines="1:25", language="elm" %}{% endcodesnippet %}

Since Elm 0.17 we no longer use signals. Instead we use a publication/subscription-pattern that uses messages. We declare the type of the message here which can:

* a `Step` with a timestamp. This represents a frame of the game-loop.
* a `KeyboardExtraMsg` which is a keyboard-input
* a `Noop` which will do nothing

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/controls/src/Hexagon.elm", lines="26:30", language="elm" %}{% endcodesnippet %}

We'll also need some constant values, e.g. the screen-sizes and the radius of the player's circle:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/controls/src/Hexagon.elm", lines="30:36", language="elm" %}{% endcodesnippet %}


== Update

We now define how the state of the game can change over time. This state-transition is done with the function `update : Msg -> Game -> Game`. This function will receive our `Msg` and will update the game-state accordingly. We distinguish here between `KeyboardExtraMsg` and `Step`:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/controls/src/Hexagon.elm", lines="93:99", language="elm" %}{% endcodesnippet %}

`onUserInput` will set the current direction based on the arrow-keys pressed on the keyboard:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/controls/src/Hexagon.elm", lines="65:80", language="elm" %}{% endcodesnippet %}

`onFrame` on the other hand will update the game's state on the next frame:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/controls/src/Hexagon.elm", lines="81:89", language="elm" %}{% endcodesnippet %}

`updatePlayer` will update the player's angle depending on the direction of the Input:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/controls/src/Hexagon.elm", lines="41:63", language="elm" %}{% endcodesnippet %}

== View

Elm provides different libraries to output html or to render 2d-graphics on a canvas. We use the `Graphics`-Package for this.

The `Player` will be a small triangle that we rotate around the game's center. A black background will represent our game-screen. We also change the `Player`'s color depending on the angle (for fun and profit):

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/controls/src/Hexagon.elm", lines="101:119", language="elm" %}{% endcodesnippet %}

The function `view : Game -> Html.Html Msg` is the main function of the view part of our application. It receives the current game-state and returns `Html`:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/controls/src/Hexagon.elm", lines="121:133", language="elm" %}{% endcodesnippet %}

== Wiring

With the `Model`, the `Update`-function and the `View` in place we are now able to wire everything together.

For this we need to construct `subscriptions`. But let's take a look at the `main`-function first (`main` is the starting point for every elm-application):

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/controls/src/Hexagon.elm", lines="161:167", language="elm" %}{% endcodesnippet %}

You'll notice that besides a `subscriptions`-function we also need an init function that defines the initial state of our application:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/controls/src/Hexagon.elm", lines="144:159", language="elm" %}{% endcodesnippet %}

Finally the `subscriptions`-function will subscribe to keyboard-events and `AnimationFrame`-events:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/controls/src/Hexagon.elm", lines="134:142", language="elm" %}{% endcodesnippet %}

== Run

Simply start `elm-reactor` in your project directory, open your browser at `http://0.0.0.0:8000/` and navigate to your sourcefile. You should see your small ship and should be able to control it with the arrow-keys <-- and -->.


