The Scene
---------

The board is made out of six triangles that touch in the center. They are alternating dark and light.
The whole scene is going to rotate around the center point as well.

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/dancefloor/src/Hexagon.elm", lines="76:89", language="elm" %}{% endcodesnippet %}

## Models
First, we define the colors for the game in the model section. They are defined in the HSL color
model (Hue, Saturation, Luminance). This is because all colors use the same hue
and saturation values. They only differ in the luminance levels.
The three colors are "dark", "medium" and "light".

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/dancefloor/src/Hexagon.elm", lines="32:36", language="elm" %}{% endcodesnippet %}

The board is going to rotate. Therefore the we add the two values `autoRotateAngle`
and `autoRotateSpeed` to the Game type:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/dancefloor/src/Hexagon.elm", lines="23:30", language="elm" %}{% endcodesnippet %}

## Creating the board
The board is made of two elements: Six triangles in alternating dark and bright
color and a center hexagon.

A triangle is defined by its three corner points. Each point is a tuple of floats.
One point in every triangle is the center point (0, 0). The other two points are
calculated using simple trigonometry. The radius depends on the canvas size.
Its length is √2 * screen width. This way the triangles always cover the whole
field.

The field itself consists of a group of Forms. Firstly we define two helper
functions: `color` returns alternating `dark` or `medium`.
`poly` creates a filled polygon from the triangle points and the color.

Then we create an array of
six elements (`[0..5]`) and use `map` to create the polygons using the helper functions.

The following functions are placed in the view section:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/dancefloor/src/Hexagon.elm", lines="134:158", language="elm" %}{% endcodesnippet %}



