Enemies
-------

In the original game the shape of the "enemies" are defined in a large class and they are created in waves. For this tutorial we keep it simpler. We have some pre-defined enemie-arrangements that repeat.

Let's first introduce a new type `Enemy`:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/enemies/src/Hexagon.elm", lines="26:30", language="elm" %}{% endcodesnippet %}


* radius: the distance of the enemies to the center
* parts: a list of true/false that indicate where the enemy has a "hole"

We add a list of enemies to the game state as well as `enemySpeed` which will increase over time. 

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/enemies/src/Hexagon.elm", lines="31:45", language="elm" %}{% endcodesnippet %}

We further define a constant values `enemyThickness` and `enemyDistance`.

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/enemies/src/Hexagon.elm", lines="63:65", language="elm" %}{% endcodesnippet %}

Our enemies are made out of trapezoids, so that they occupy 1-5 sectors of the hexagon. We configure one enemy with an array of booleans, where `True` indicates an occupied sector and `False` a hole. We define a fixed set of enemies:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/enemies/src/Hexagon.elm", lines="66:77", language="elm" %}{% endcodesnippet %}

You can chose whatever config you like, just make sure that you keep one side open ;-)

As you noticed, we have only defined the `parts` property of the Enemy type yet. The radius will represent the distance to the center (and therefore to the player) and we will calculate it in the update-function.


== Updating radius

This part is a little bit tricky. Let's first introduce two new function that update `enemies` and `enemySpeed` on the game state in the `onFrame`-Function:

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/enemies/src/Hexagon.elm", lines="178:200", language="elm" %}{% endcodesnippet %}

`updateEnemySpeed` will increase `enemySpeed` over time starting with an initial value

{% codesnippet "https://raw.githubusercontent.com/macrozone/elm-hexagon-tutorial/chapter/enemies/src/Hexagon.elm", lines="148:150", language="elm" %}{% endcodesnippet %}


