Elm Game Tutorial
-----------------

In this tutorial we are going to create a game in elm. The game is based on
Terry Cavanagh's great arcade game http://terrycavanaghgames.com/hexagon/[Hexagon].
That game was the prototype for the successful mobile game Super Hexagon.

The tutorial requires some knowledge of the concept of functional programming.
You should also have read the section about
[the Elm architecture](http://guide.elm-lang.org/architecture/index.html). The game is building
on it.

It is based on Elm 0.17 which uses a different approach than 0.16. In fact we were almost done with
the tutorial when 0.17 came out and dropped Signals in favor of Commands. So we decided to
rewrite everything to be 0.17 compliant and use the new architecture.

The ecosystem is not complete yet and the move to a new API broke a few useful tools like the Elm
debugger.

While Elm is currently only compiling to Javascript this might change in the future. That's why
it is not possible anymore to have external librarys that use native bindings such as the Web audio API.
Until Elm core supports this we are going to have to work around this limitation (as you will
see in chapter <<music.adoc#music,Music>>.

The tutorial is is split up in seven chapters each with a special focus. At the end of each
chapter you will have a running program.
